# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1grV9wS6vapaM83BUCNy-loiYJdLu2bZR
"""

import pandas as pd
import jieba
from sklearn.feature_selection import chi2
from sklearn.feature_selection import mutual_info_classif
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import numpy as np
import random

random.seed(42)
np.random.seed(42)

from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

class CentroidClassifier:
    def __init__(self):
        self.centroids = {}

    def fit(self, X, y):
        """
        训练质心分类器
        X: 特征矩阵 (numpy 数组或稀疏矩阵, 每行是一个样本)
        y: 标签 (numpy 数组)
        """
        unique_classes = np.unique(y)
        for cls in unique_classes:
            # 选择属于该类别的所有样本
            cls_samples = X[y == cls]
            # 计算质心（每列取均值）
            self.centroids[cls] = np.mean(cls_samples, axis=0)

    def predict(self, X):
        """
        预测标签
        X: 输入样本矩阵
        返回: 预测的类别标签
        """
        predictions = []
        for sample in X:
            # 计算样本与所有质心的距离（可以使用欧几里得距离或余弦相似度）
            distances = {cls: np.linalg.norm(sample - centroid) for cls, centroid in self.centroids.items()}
            # 找到距离最近的类别
            predictions.append(min(distances, key=distances.get))
        return np.array(predictions)
class BalancedWinnow:
    def __init__(self, alpha=1.2, beta=0.8, threshold=1.0, w_plus_init=2.0, w_minus_init=1.0):
        self.alpha = alpha
        self.beta = beta
        self.threshold = threshold
        self.w_plus_init = w_plus_init
        self.w_minus_init = w_minus_init
        self.w_plus = None
        self.w_minus = None

    def fit(self, X, y, epochs=1):
        num_features = X.shape[1]
        self.w_plus = np.full(num_features, self.w_plus_init)
        self.w_minus = np.full(num_features, self.w_minus_init)

        for _ in range(epochs):
            for xi, yi in zip(X, y):
                weighted_sum = np.dot(self.w_plus - self.w_minus, xi)
                prediction = 1 if weighted_sum >= self.threshold else 0
                if prediction != yi:  # 更新权重
                    if yi == 1:  # 正例错误
                        self.w_plus[xi > 0] *= self.alpha
                        self.w_minus[xi > 0] *= self.beta
                    else:  # 负例错误
                        self.w_plus[xi > 0] *= self.beta
                        self.w_minus[xi > 0] *= self.alpha

    def predict(self, X):
        predictions = []

        for xi in X:
            weighted_sum = np.dot(self.w_plus - self.w_minus, xi)
            predictions.append(1 if weighted_sum >= self.threshold else 0)
        return np.array(predictions)

# 找最优K值
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
